spring.application.name=AttendEase API


# MYSQL PROPERTIES
spring.datasource.url=jdbc:mysql://yamanote.proxy.rlwy.net:58298/railway?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=OkYNfnMxIZLxUZtgElpREQtxCNQRtjEX
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#JWT
jwt.secret.key=43b90ca18ef3430d8092fb931ea6292f
jwt.token.expiration.time=3600000